db:
  image: mysql
  command: tail -f /dev/null
  environment:
   - MYSQL_ROOT_PASSWORD=password
web:
  build: .
  ports:
   - 80:80
   - 443:443
  links:
   - db
  # volumes:
  #  - /local/data/dir:/data:rw
  environment:
   - MEDIAWIKI_DB_PASSWORD=password
